export type ImageSourceType = 'real' | 'licensed' | 'generated' | 'illustrative';

export interface ImageAsset {
  src: string;
  alt: string;
  subject: string;
  sourceType: ImageSourceType;
  aspectRatio?: string;
  dimensions?: { width: number; height: number };
  objectPosition?: string;
  desktopPosition?: string;
  mobilePosition?: string;
}

export const imageAssets = {
  // 1. India Visuals (Lookbook concept imagery)
  india: {
    hero: {
      src: '/images/jaisalmer/hero-folkmiles.png',
      alt: 'Explore India by Locals — Jaisalmer Golden Fort architecture at sunrise',
      subject: 'Jaisalmer Golden Fort architecture',
      sourceType: 'real',
      aspectRatio: '1916/821',
      dimensions: { width: 1916, height: 821 },
      objectPosition: 'right center',
      desktopPosition: 'right center',
      mobilePosition: '75% center',
    },
    mountains: {
      src: '/images/india/himalayas.jpg',
      alt: 'Himalayan mountain valleys and high ridges',
      subject: 'Himalayan valleys',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 40%',
      desktopPosition: 'center 40%',
      mobilePosition: 'center 40%',
    },
    heritage: {
      src: '/images/india/heritage.jpg',
      alt: 'Historic stone architecture and ancient forts of India',
      subject: 'Indian heritage monuments',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    natureCoast: {
      src: '/images/india/kerala.jpg',
      alt: 'Traditional wooden boat floating on Kerala backwaters',
      subject: 'Kerala backwaters and coast',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 55%',
      desktopPosition: 'center 55%',
      mobilePosition: 'center 55%',
    },
    culturePeople: {
      src: '/images/india/street.jpg',
      alt: 'Vibrant local bazaar with spices, street food and everyday life',
      subject: 'Street culture and markets',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 45%',
      desktopPosition: 'center 45%',
      mobilePosition: 'center 45%',
    },
  },

  // 2. Rajasthan Visuals (Lookbook concept imagery)
  rajasthan: {
    hawaMahal: {
      src: '/images/rajasthan/hawa-mahal.jpg',
      alt: 'Intricate pink sandstone facade of Hawa Mahal, Jaipur',
      subject: 'Hawa Mahal, Jaipur',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 35%',
      desktopPosition: 'center 35%',
      mobilePosition: 'center 35%',
    },
    udaipur: {
      src: '/images/rajasthan/udaipur.jpg',
      alt: 'Lake Pichola palace ghats reflected in calm water at Udaipur',
      subject: 'Lake Pichola, Udaipur',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 45%',
      desktopPosition: 'center 45%',
      mobilePosition: 'center 45%',
    },
    jodhpur: {
      src: '/images/rajasthan/jodhpur.jpg',
      alt: 'Mehrangarh Fort towering above the Blue City of Jodhpur',
      subject: 'Mehrangarh Fort & Blue City, Jodhpur',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 40%',
      desktopPosition: 'center 40%',
      mobilePosition: 'center 40%',
    },
    musician: {
      src: '/images/rajasthan/musician.jpg',
      alt: 'Rajasthani folk musician playing a traditional stringed instrument',
      subject: 'Folk musician with kamaicha',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 30%',
      desktopPosition: 'center 30%',
      mobilePosition: 'center 30%',
    },
    textiles: {
      src: '/images/rajasthan/textiles.jpg',
      alt: 'Hand block-printed textiles drying in the courtyard sunshine',
      subject: 'Rajasthan block print craft',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    caravan: {
      src: '/images/rajasthan/caravan.jpg',
      alt: 'Camel caravan silhouetted along the desert dunes at sunset',
      subject: 'Camel caravan in the desert',
      sourceType: 'generated',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 45%',
      desktopPosition: 'center 45%',
      mobilePosition: 'center 45%',
    },
  },

  // 3. Jaisalmer Visuals (Strictly genuine FolkMiles & verified project photography)
  jaisalmer: {
    fort: {
      src: '/fort.jpg',
      alt: 'Jaisalmer Fort glowing at sunset above the Golden City',
      subject: 'Jaisalmer Fort (Sonar Qila) sunset panorama',
      sourceType: 'real',
      aspectRatio: '4:3',
      dimensions: { width: 2560, height: 1920 },
      objectPosition: 'center 40%',
      desktopPosition: 'center 40%',
      mobilePosition: 'center 38%',
    },
    fortPalace: {
      src: '/images/jaisalmer/fort-palace.jpg',
      alt: 'Maharaja Mahal inside Jaisalmer Fort — Grand sandstone palace facade and archway',
      subject: 'Maharaja Mahal (Fort Palace Museum & Heritage Centre)',
      sourceType: 'real',
      aspectRatio: '4:3',
      dimensions: { width: 2400, height: 1800 },
      objectPosition: 'center 35%',
      desktopPosition: 'center 35%',
      mobilePosition: 'center 30%',
    },
    livingLanes: {
      src: '/images/jaisalmer/living-lanes.jpg',
      alt: 'Cobblestone living lane winding through the golden sandstone quarters of Sonar Qila',
      subject: 'Old living lanes inside Jaisalmer Fort',
      sourceType: 'real',
      aspectRatio: '3:4',
      dimensions: { width: 1800, height: 2400 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 55%',
    },
    nathmalHaveli: {
      src: '/images/jaisalmer/nathmal-haveli.jpg',
      alt: 'Intricately carved sandstone facade of Nathmal Ki Haveli with carved stone elephants',
      subject: 'Nathmal Ki Haveli facade',
      sourceType: 'real',
      aspectRatio: '3:4',
      dimensions: { width: 1105, height: 1423 },
      objectPosition: 'center 30%',
      desktopPosition: 'center 30%',
      mobilePosition: 'center 25%',
    },
    salimSinghHaveli: {
      src: '/images/jaisalmer/salim-singh-haveli.jpg',
      alt: 'Arched peacock roofline and upper balconies of Salim Singh Ki Haveli (Moti Mahal)',
      subject: 'Salim Singh Ki Haveli (Moti Mahal)',
      sourceType: 'real',
      aspectRatio: '4:5',
      dimensions: { width: 412, height: 485 },
      objectPosition: 'center 40%',
      desktopPosition: 'center 40%',
      mobilePosition: 'center 35%',
    },
    haveliDetail: {
      src: '/images/jaisalmer/haveli-detail.jpg',
      alt: 'Three-storey sandstone haveli wall displaying intricate geometric jali lattice and floral carvings',
      subject: 'Sandstone jali carving detail on haveli wall',
      sourceType: 'real',
      aspectRatio: '3:4',
      dimensions: { width: 1800, height: 2400 },
      objectPosition: 'center 40%',
      desktopPosition: 'center 40%',
      mobilePosition: 'center 35%',
    },
    amarSagar: {
      src: '/images/jaisalmer/amar-sagar.jpg',
      alt: 'Amar Sagar lake and stone pavilions reflected in water before the Jain temple complex',
      subject: 'Amar Sagar Lake & Pavilions',
      sourceType: 'real',
      aspectRatio: '16:9',
      dimensions: { width: 1689, height: 931 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    badaBagh: {
      src: '/images/jaisalmer/bada-bagh.jpg',
      alt: 'Royal cenotaph chhatri of the Maharawals at Bada Bagh framed through a stone arch',
      subject: 'Bada Bagh Royal Cenotaphs',
      sourceType: 'real',
      aspectRatio: '6:5',
      dimensions: { width: 610, height: 503 },
      objectPosition: 'center 42%',
      desktopPosition: 'center 42%',
      mobilePosition: 'center 42%',
    },
    dancerCamel: {
      src: '/images/jaisalmer/real-dancer-camel.jpg',
      alt: 'Authentic Kalbelia folk dancer in traditional mirror-work dress with decorated camel at desert camp',
      subject: 'Kalbelia folk dancer with camel at desert camp',
      sourceType: 'real',
      aspectRatio: '3:2',
      dimensions: { width: 1600, height: 1066 },
      objectPosition: 'center 30%',
      desktopPosition: 'center 30%',
      mobilePosition: 'center 25%',
    },
    campFire: {
      src: '/images/jaisalmer/camp-fire.jpg',
      alt: 'Dramatic fireside desert performance with fire breather and guests seated around the hearth',
      subject: 'Fireside performance & fire breather at camp',
      sourceType: 'real',
      aspectRatio: '4:3',
      dimensions: { width: 1448, height: 1086 },
      objectPosition: 'center 35%',
      desktopPosition: 'center 35%',
      mobilePosition: 'center 30%',
    },
    campTwilight: {
      src: '/images/jaisalmer/camp-twilight.jpg',
      alt: 'Illuminated luxury desert camp at twilight with sculpted lantern tree and white Swiss tents',
      subject: 'Luxury Swiss tent camp at twilight',
      sourceType: 'real',
      aspectRatio: '4:3',
      dimensions: { width: 1448, height: 1086 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    campSunset: {
      src: '/images/jaisalmer/camp-sunset.jpg',
      alt: 'Swiss tents at desert camp in Jaisalmer glowing under sunset sky',
      subject: 'Desert camp Swiss tents at sunset',
      sourceType: 'real',
      aspectRatio: '4:3',
      dimensions: { width: 1448, height: 1086 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    campDance: {
      src: '/images/jaisalmer/camp-dance.jpg',
      alt: 'Authentic Bhavai folk dancer balancing stacked brass pots on head around the camp fire',
      subject: 'Bhavai dancer with stacked pots at camp',
      sourceType: 'real',
      aspectRatio: '4:3',
      dimensions: { width: 1448, height: 1086 },
      objectPosition: 'center 45%',
      desktopPosition: 'center 45%',
      mobilePosition: 'center 40%',
    },
    camelDunes: {
      src: '/images/jaisalmer/real-camel-dunes.jpg',
      alt: 'Authentic camel resting on wind-sculpted sand dunes under open desert sky at sunset',
      subject: 'Camel on Thar sand dunes at sunset',
      sourceType: 'real',
      aspectRatio: '3:2',
      dimensions: { width: 1536, height: 1024 },
      objectPosition: 'center 40%',
      desktopPosition: 'center 40%',
      mobilePosition: 'center 40%',
    },
    tentRoyal: {
      src: '/images/jaisalmer/tent-interior-royal.jpg',
      alt: 'Royal tent suite interior with polished wooden floor, four-poster beds and Rajasthani furnishings',
      subject: 'Royal tent suite interior',
      sourceType: 'real',
      aspectRatio: '3:2',
      dimensions: { width: 1536, height: 1024 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    tentLuxury: {
      src: '/images/jaisalmer/tent-interior-luxury.jpg',
      alt: 'Luxury Swiss tent suite interior with four-poster bed and butterfly leather chairs',
      subject: 'Luxury tent suite interior',
      sourceType: 'real',
      aspectRatio: '4:3',
      dimensions: { width: 1448, height: 1086 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    tharLandscape: {
      src: '/images/jaisalmer/thar-landscape.jpg',
      alt: 'Critically endangered Great Indian Bustards (Godawan) in their natural Thar arid habitat at Desert National Park',
      subject: 'Great Indian Bustards at Desert National Park near Jaisalmer',
      sourceType: 'real',
      aspectRatio: '16:10',
      dimensions: { width: 713, height: 429 },
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
    tharNight: {
      src: '/images/jaisalmer/thar-night.jpg',
      alt: 'Starlit night sky over the Thar Desert with silhouette of a desert tree (Illustrative Concept Visual)',
      subject: 'Thar Desert night sky (Illustrative concept visual)',
      sourceType: 'illustrative',
      aspectRatio: '16:10',
      dimensions: { width: 763, height: 465 },
      objectPosition: 'center 30%',
      desktopPosition: 'center 30%',
      mobilePosition: 'center 30%',
    },
    desert: {
      src: '/desert.jpg',
      alt: 'Sweeping wind-rippled sand dunes in the Thar Desert near Jaisalmer',
      subject: 'Sam Dunes, Thar Desert',
      sourceType: 'real',
      aspectRatio: '3:2',
      dimensions: { width: 3872, height: 2592 },
      objectPosition: 'center 60%',
      desktopPosition: 'center 60%',
      mobilePosition: 'center 55%',
    },
    heritage: {
      src: '/heritage.jpg',
      alt: 'Intricate sandstone jali carvings and wooden window shutters on Patwon Ki Haveli',
      subject: 'Patwon Ki Haveli stone carvings',
      sourceType: 'real',
      aspectRatio: '3:2',
      dimensions: { width: 1280, height: 853 },
      objectPosition: 'center 45%',
      desktopPosition: 'center 45%',
      mobilePosition: 'center 40%',
    },
  },

  // 4. Curated Itinerary Starting Visuals (Standardized 16:10)
  itineraries: {
    '2-days-1-night': {
      src: '/images/jaisalmer/fort-palace.jpg',
      alt: '2 Days 1 Night Jaisalmer Itinerary — Living fort, Maharaja Mahal and old city havelis',
      subject: 'Maharaja Mahal / Jaisalmer Fort Palace',
      sourceType: 'real',
      aspectRatio: '16:10',
      objectPosition: 'center 35%',
      desktopPosition: 'center 35%',
      mobilePosition: 'center 30%',
    },
    '3-days-2-nights': {
      src: '/images/jaisalmer/real-camel-dunes.jpg',
      alt: '3 Days 2 Nights Jaisalmer Itinerary — Balanced city exploration, camel safari and desert night',
      subject: 'Camel on dunes at sunset',
      sourceType: 'real',
      aspectRatio: '16:10',
      objectPosition: 'center 40%',
      desktopPosition: 'center 40%',
      mobilePosition: 'center 40%',
    },
    '4-days-3-nights': {
      src: '/images/jaisalmer/amar-sagar.jpg',
      alt: '4 Days 3 Nights Jaisalmer Itinerary — Slow travel, Amar Sagar lake pavilions, Jain temples and desert dunes',
      subject: 'Amar Sagar lake pavilions & Jain temple',
      sourceType: 'real',
      aspectRatio: '16:10',
      objectPosition: 'center 50%',
      desktopPosition: 'center 50%',
      mobilePosition: 'center 50%',
    },
  },

  // 5. Curated Experience Visuals (Standardized 4:3)
  experiences: {
    'jaisalmer-desert-safari': {
      src: '/desert.jpg',
      alt: 'Thar Desert Safari — Sand dunes, camel journeys, luxury camp evening and starlit skies',
      subject: 'Sam Dunes, Thar Desert',
      sourceType: 'real',
      aspectRatio: '4:3',
      objectPosition: 'center 60%',
      desktopPosition: 'center 60%',
      mobilePosition: 'center 55%',
    },
    'jaisalmer-fort-heritage': {
      src: '/heritage.jpg',
      alt: 'Jaisalmer Fort & Heritage — Living cobblestone lanes, royal palaces and intricately carved havelis',
      subject: 'Patwon Ki Haveli jali carvings',
      sourceType: 'real',
      aspectRatio: '4:3',
      objectPosition: 'center 45%',
      desktopPosition: 'center 45%',
      mobilePosition: 'center 40%',
    },
  },
} as const;

export type ImageAssetKeys = typeof imageAssets;
