import {notFound} from 'next/navigation';
import Link from 'next/link';
import {ArrowRight} from 'lucide-react';
import {Button,Breadcrumbs,CTA,Eyebrow} from '@/components/ui';
import {EnquiryForm} from '@/components/enquiry-form';
import {pages,legalPages} from '@/lib/content';
import {metadata,BreadcrumbSchema} from '@/lib/seo';
import {brand} from '@/lib/config';
const fixed=['about','b2b-travel-partners','local-partners','privacy-policy','terms-and-conditions','cancellation-policy','contact'];
export function generateStaticParams(){return fixed.map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(slug==='contact')return metadata('Contact FolkMiles','Make a Jaisalmer trip or travel-partner enquiry with FolkMiles.','/contact');const p=pages[slug]||legalPages[slug];return p?metadata(p.title,p.description,`/${slug}`):{title:'Not found'}}
function Contact(){const hasContact=brand.email||brand.whatsapp||brand.address;return <><div className="wrap"><Breadcrumbs items={[{label:'Contact'}]}/></div><section className="form-section"><div className="section wrap form-layout"><div><Eyebrow>Begin with Jaisalmer</Eyebrow><h1>What does your<br/><em>journey look like?</em></h1><p>Tell us the basics and we’ll prepare a considered reply. An enquiry does not reserve a service or confirm a booking.</p>{hasContact?<div className="contact-links">{brand.email&&<a className="text-link" href={`mailto:${brand.email}`} data-event="email_click">{brand.email}</a>}{brand.whatsapp&&<a className="text-link" href={`https://wa.me/${brand.whatsapp}`} data-event="whatsapp_click">WhatsApp</a>}{brand.address&&<span>{brand.address}</span>}</div>:<p className="form-note">Contact details will appear here once official business email, phone or address are configured.</p>}<p className="form-note">This site does not provide emergency assistance. For an active, confirmed trip, use the emergency contact in your travel documents.</p></div><EnquiryForm kind="traveller"/></div></section><CTA/></>}
export default async function StaticPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(slug==='contact')return <Contact/>;const p=pages[slug]||legalPages[slug];if(!p)notFound();const b2b=slug==='b2b-travel-partners';const partner=slug==='local-partners';const legal=!!legalPages[slug];return <><div className="wrap"><Breadcrumbs items={[{label:p.eyebrow},{label:p.title}]}/></div><section className="page-intro wrap"><Eyebrow>{p.eyebrow}</Eyebrow><h1>{p.title}</h1><p>{p.description}</p></section><section className="section wrap editorial-layout"><div className="prose">{p.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.body}</p></section>)}{legal&&<p className="quote-note"><strong>Internal launch note:</strong> This editable policy draft requires professional legal review, the contracting entity and official contact details before it can be treated as a final public policy.</p>}{slug==='about'&&<Link className="text-link" href="/contact">Plan a Jaisalmer journey <ArrowRight size={16}/></Link>}</div>{b2b||partner?<aside className="sidebar"><Eyebrow>{b2b?'Send a Jaisalmer brief':'Apply to partner'}</Eyebrow><h3>{b2b?'Travel-agent enquiry':'Tell us about your service.'}</h3><p>{b2b?'We will respond when operational contact details and an enquiry delivery service are configured.':'An application starts a review; it does not mean approval, verification or a booking guarantee.'}</p></aside>:<aside className="sidebar"><Eyebrow>Explore by Locals</Eyebrow><h3>Beginning in Jaisalmer.</h3><p>FolkMiles is building destination-level local networks across India. Other destinations are coming later and are not currently bookable.</p><Button href="/contact" event="plan_trip_click">Plan My Trip</Button></aside>}</section>{b2b||partner?<section className="form-section"><div className="section wrap form-layout"><div><Eyebrow>{b2b?'Jaisalmer ground handling':'For the people who make a place'}</Eyebrow><h2>{b2b?'Send your client brief.':'Start an application.'}</h2><p>{b2b?'Please share only the information needed for a quotation. Do not send client identity documents or payment data through this form.':'Please describe your current service accurately. A follow-up may request business, safety or service documents through an agreed channel.'}</p></div><EnquiryForm kind={b2b?'b2b':'partner'}/></div></section>:null}{!legal&&!b2b&&!partner&&<CTA/>}<BreadcrumbSchema items={[{label:p.eyebrow,path:`/${slug}`}]}/></>}
