'use client';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import Script from 'next/script';
import {brand} from '@/lib/config';
declare global {interface Window {dataLayer:unknown[];gtag?:(...args:unknown[])=>void;fbq?:(...args:unknown[])=>void;}}
export function track(event:string){if(localStorage.getItem('fm-consent')!=='accepted')return;window.dataLayer=window.dataLayer||[];window.dataLayer.push({event});if(brand.ga)window.gtag?.('event',event);}
export function Analytics(){const [consent,setConsent]=useState<string|null>(null);const [show,setShow]=useState(false);const path=usePathname();const configured=!!(brand.ga||brand.gtm||brand.pixel);
useEffect(()=>{const saved=localStorage.getItem('fm-consent');const timer=setTimeout(()=>{setConsent(saved);setShow(configured&&!saved)},0);function click(e:MouseEvent){const el=(e.target as HTMLElement).closest<HTMLElement>('[data-event],[data-consent-settings]');if(el?.hasAttribute('data-consent-settings'))setShow(true);if(el?.dataset.event)track(el.dataset.event)}document.addEventListener('click',click);return()=>{clearTimeout(timer);document.removeEventListener('click',click)}},[configured]);
useEffect(()=>{if(consent==='accepted'&&path.includes('/destinations/jaisalmer/'))track('jaisalmer_package_view')},[path,consent]);
function choose(value:string){localStorage.setItem('fm-consent',value);setConsent(value);setShow(false);if(value==='declined'&&consent==='accepted')window.location.reload()}
return <>{consent==='accepted'&&<>{/^G-[A-Z0-9]+$/.test(brand.ga)&&!brand.gtm&&<><Script src={`https://www.googletagmanager.com/gtag/js?id=${brand.ga}`}/><Script id="ga-init">{`window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};gtag('js',new Date());gtag('config','${brand.ga}');`}</Script></>}{/^GTM-[A-Z0-9]+$/.test(brand.gtm)&&<Script id="gtm-init">{`window.dataLayer=window.dataLayer||[];window.dataLayer.push({'gtm.start':new Date().getTime(),event:'gtm.js'});var s=document.createElement('script');s.src='https://www.googletagmanager.com/gtm.js?id=${brand.gtm}';document.head.appendChild(s);`}</Script>}{/^\d+$/.test(brand.pixel)&&<Script id="meta-pixel">{`!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${brand.pixel}');fbq('track','PageView');`}</Script>}</>}{show&&<aside className="cookie-banner" aria-label="Optional analytics preferences"><p>{configured?'Allow optional analytics to help us understand how this website is used? You can change your choice at any time.':'Optional analytics is currently disabled. No optional tracking scripts are loaded.'}</p><div className="button-row">{configured&&<button className="button" onClick={()=>choose('accepted')}>Allow analytics</button>}<button className="button secondary" onClick={()=>choose('declined')}>{configured?'Decline':'Close'}</button></div></aside>}</>}
