'use client';
import {useState} from 'react';
import Link from 'next/link';
import {track} from './analytics';
import {schemas} from '@/lib/forms';
type Kind='traveller'|'b2b'|'partner'; type State={status:'idle'|'sending'|'success'|'error';message?:string;errors?:Record<string,string[]>};
const traveller=[['fullName','Full name','text'],['phone','Phone number','tel'],['email','Email','email'],['city','Your city','text'],['travelDates','Travel month or dates','text'],['adults','Adults','number'],['children','Children','number'],['duration','Trip duration','select:Choose a duration|2 days / 1 night|3 days / 2 nights|4 days / 3 nights|Not sure yet'],['stayPreference','Stay preference','select:Choose a preference|Comfortable|Premium|Desert camp|Mix of city and desert|Not sure yet'],['budget','Approximate budget range','select:Choose a range|Value conscious|Comfortable|Premium|Would like guidance'],['interests','Interests','text'],['pickup','Pickup requirement','select:Choose a preference|Airport pickup|Railway station pickup|I will arrange it|Not sure yet'],['message','Anything else we should know?','textarea']];
const b2b=[['contactName','Contact name','text'],['agency','Agency or business name','text'],['phone','Phone','tel'],['email','Email','email'],['city','City','text'],['websiteOrSocial','Website or social profile','url'],['travelDates','Client travel dates','text'],['travellers','Number of travellers','number'],['services','Required services','text'],['budget','Budget level','select:Choose a level|Value conscious|Comfortable|Premium|Would like guidance'],['requirements','Additional requirements','textarea']];
const partner=[['contactName','Contact name','text'],['business','Business or service name','text'],['category','Service category','select:Choose a category|Hotel or homestay|Desert camp|Transport provider|Local guide|Food or craft host|Activity operator|Other'],['phone','Phone','tel'],['email','Email','email'],['serviceArea','Service area','text'],['websiteOrSocial','Website or social profile','url'],['message','Tell us about your service','textarea']];
function Input({field,error}:{field:string[];error?:string[]}){const [name,label,type]=field;const id=`field-${name}`;const common={id,name,required:!['interests','pickup','message','websiteOrSocial','requirements'].includes(name),'aria-invalid':!!error,'aria-describedby':error?`${id}-error`:undefined};if(type==='textarea')return <div className="field full"><label htmlFor={id}>{label}</label><textarea {...common}/>{error&&<p className="field-error" id={`${id}-error`}>{error[0]}</p>}</div>;if(type.startsWith('select:')){const opts=type.slice(7).split('|');return <div className="field"><label htmlFor={id}>{label}</label><select {...common} defaultValue="">{opts.map((o,i)=><option value={i?o:''} key={o} disabled={!i}>{o}</option>)}</select>{error&&<p className="field-error" id={`${id}-error`}>{error[0]}</p>}</div>}return <div className="field"><label htmlFor={id}>{label}</label><input type={type} {...common} min={type==='number'?'0':undefined}/>{error&&<p className="field-error" id={`${id}-error`}>{error[0]}</p>}</div>}
export function EnquiryForm({kind}:{kind:Kind}){const [state,setState]=useState<State>({status:'idle'});const fields=kind==='traveller'?traveller:kind==='b2b'?b2b:partner;const title=kind==='traveller'?'Start planning':'Send a partner request';async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setState({status:'sending'});const data=Object.fromEntries(new FormData(e.currentTarget));const validated=schemas[kind].safeParse(data);if(!validated.success){setState({status:'error',message:'Please review the highlighted fields.',errors:validated.error.flatten().fieldErrors});return}const endpoint=process.env.NEXT_PUBLIC_ENQUIRY_ENDPOINT;if(!endpoint){setState({status:'error',message:'Enquiries are not connected yet. Please use an available contact option once it has been configured.'});return}try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data})});const body=await r.json() as State;if(!r.ok){setState({status:'error',message:body.message,errors:body.errors});return}setState({status:'success',message:body.message});track(kind==='traveller'?'traveller_form_submission':kind==='b2b'?'b2b_form_submission':'local_partner_application');e.currentTarget.reset()}catch{setState({status:'error',message:'We could not send this enquiry. Please try again later or use an available contact option.'})}}return <form className="enquiry-form" onSubmit={submit} noValidate><h2>{title}</h2><p className="form-note">Fields marked as required help us prepare a relevant response.</p>{state.status==='success'&&<div className="form-status success" role="status">{state.message}</div>}{state.status==='error'&&<div className="form-status" role="alert">{state.message}</div>}<div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><div className="form-grid">{fields.map(f=><Input key={f[0]} field={f} error={state.errors?.[f[0]]}/>)}</div><label className="consent"><input name="consent" type="checkbox" value="true" required aria-invalid={!!state.errors?.consent}/><span>I agree that FolkMiles may use these details to respond to this request, as described in the <Link href="/privacy-policy">privacy policy</Link>.</span></label>{state.errors?.consent&&<p className="field-error">{state.errors.consent[0]}</p>}<p className="form-note">This is an enquiry, not a booking. A trip is confirmed only after the required payment clears and each critical service is confirmed in writing.</p><button className="button" disabled={state.status==='sending'}>{state.status==='sending'?'Sending…':kind==='partner'?'Apply to partner':'Send enquiry'}</button></form>}
