import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Compass, Handshake, MapPin } from 'lucide-react';
import { tours, faqs } from '@/lib/content';
import { quoteNote } from '@/lib/config';

export function Button({href,children,secondary=false,event}:{href:string;children:React.ReactNode;secondary?:boolean;event?:string}){return <Link href={href} className={`button ${secondary?'secondary':''}`} data-event={event}>{children}<ArrowUpRight size={18}/></Link>}
export function Photo({name,alt,priority=false,className=''}:{name:string;alt:string;priority?:boolean;className?:string}){return <div className={`photo ${className}`}><Image src={`/${name}.jpg`} alt={alt} fill sizes="(max-width: 760px) 100vw, 60vw" priority={priority} quality={85}/></div>}
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
export function SectionTitle({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <div className="section-title"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div>{children}</div>}
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">Home</Link>{items.map((item,i)=><span key={i}><span aria-hidden="true">/</span>{item.href?<Link href={item.href}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}</span>)}</nav>}
export function TrustStrip(){return <div className="trust-strip wrap"><div><Compass/><span>Local knowledge.<small>A more thoughtful way to travel.</small></span></div><div><Handshake/><span>Clear, personal planning.<small>Your journey, shaped around you.</small></span></div><div><MapPin/><span>One destination at a time.<small>Beginning with Jaisalmer.</small></span></div></div>}
export function TourCards(){return <div className="tour-grid">{tours.map((t,i)=><Link className="tour-card" key={t.slug} href={`/destinations/jaisalmer/${t.slug}`}><div className="tour-number">0{i+1}<ArrowUpRight size={24}/></div>{i===1&&<span className="recommend">Our recommended balance</span>}<p className="eyebrow">{t.duration}</p><h3>{t.short}</h3><p>{t.description}</p><span className="text-link">Discover this trip <ArrowRight size={16}/></span></Link>)}</div>}
export function Experiences(){return <section className="section wrap" id="experiences"><SectionTitle eyebrow="Go beyond the postcard" title="Come for the place. Stay for the stories."/><div className="experience-grid"><Link className="experience-card" href="/experiences/jaisalmer-desert-safari"><Photo name="desert" alt="Wind-shaped sand dunes in the Thar Desert near Jaisalmer"/><div><Eyebrow>Space to slow down</Eyebrow><h3>Into the Thar Desert <ArrowUpRight/></h3><p>Open skies, shifting sands and an evening at your pace.</p></div></Link><Link className="experience-card" href="/experiences/jaisalmer-fort-heritage"><Photo name="heritage" alt="Intricately carved sandstone exterior of Patwon ki Haveli"/><div><Eyebrow>Look a little closer</Eyebrow><h3>Inside the Golden City <ArrowUpRight/></h3><p>Living lanes, carved stone and the people between.</p></div></Link></div></section>}
export function FAQ(){return <section className="section wrap faq"><div><Eyebrow>A few useful answers</Eyebrow><h2>Before you pack.</h2><p>Still wondering about something?<br/><Link className="text-link" href="/contact">Tell us what you have in mind <ArrowRight size={16}/></Link></p></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>}
export function CTA(){return <section className="cta"><div className="wrap cta-inner"><div><Eyebrow>Your next story starts here</Eyebrow><h2>Let’s make it<br/><em>your kind of journey.</em></h2><p>Tell us a little about your Jaisalmer plans.<br/>We’ll take it from there, together.</p></div><Button href="/contact" event="plan_trip_click">Plan My Trip</Button></div></section>}
export function QuoteNote(){return <p className="quote-note">{quoteNote}</p>}
