import {notFound} from 'next/navigation';
import {Button,Breadcrumbs,CTA,Eyebrow,Photo,QuoteNote} from '@/components/ui';
import {pages} from '@/lib/content';
import {metadata,BreadcrumbSchema,JsonLd} from '@/lib/seo';
import {brand} from '@/lib/config';
const valid=['jaisalmer-desert-safari','jaisalmer-fort-heritage'];
export function generateStaticParams(){return valid.map(experience=>({experience}))}
export async function generateMetadata({params}:{params:Promise<{experience:string}>}){const {experience}=await params;const p=pages[`experiences/${experience}`];return p?metadata(p.eyebrow,p.description,`/experiences/${experience}`):{title:'Not found'}}
export default async function Experience({params}:{params:Promise<{experience:string}>}){const {experience}=await params;const p=pages[`experiences/${experience}`];if(!p)notFound();return <><div className="wrap"><Breadcrumbs items={[{label:'Experiences',href:'/#experiences'},{label:p.eyebrow}]}/></div><section className="page-intro wrap"><Eyebrow>{p.eyebrow}</Eyebrow><h1>{p.title}</h1><p>{p.description}</p></section>{p.image&&<div className="wrap wide-photo"><Photo name={p.image} alt={p.image==='desert'?'Rolling dunes in the Thar Desert near Jaisalmer':'Detailed sandstone carvings on Patwon ki Haveli in Jaisalmer'}/></div>}<section className="section wrap editorial-layout"><div className="prose">{p.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.body}</p></section>)}<QuoteNote/></div><aside className="sidebar"><Eyebrow>Plan it well</Eyebrow><h3>Start with a conversation.</h3><p>Share your dates and group so we can discuss a suitable experience and what is currently available.</p><Button href="/contact" event="package_enquiry_click">Make an enquiry</Button></aside></section><CTA/><BreadcrumbSchema items={[{label:'Experiences',path:'/#experiences'},{label:p.eyebrow,path:`/experiences/${experience}`}]}/><JsonLd value={{'@context':'https://schema.org','@type':'TouristTrip',name:p.eyebrow,description:p.description,...(brand.domain?{url:`${brand.domain}/experiences/${experience}`}:{})}}/></>}
